#ifndef _CONSTANT_H_
#define _CONSTANT_H_
#define _MAX_CONFIG_SIZE 100
#define MAX_COMMIT_MESSAGE 72
#define ID_LEN 10
#define FILE_COLOR FOREGROUND_BLUE||FOREGROUND_GREEN // ||FOREGROUND_RED
#define FOLDER_COLOR FOREGROUND_BLUE
#define _MAX_CONFIG_ALIAS_SIZE 200
#endif